### ISSUE TITLE
Issues deploying a custom build - cdk deploy -> Error: Failed to bundle asset DocUnderstanding/WebApp

### ISSUE THREAD

**Issue by jaristizabalc** [aws-solutions/enhanced-document-understanding-on-aws#12]
**Describe the bug**
Issues deploying the solution with a custom build.  cdk deploy command  failes to bundle assets.

**To Reproduce**
I have installed all the dependencies, however cdk version is 2.103.1, I have not been able to find v2.36.0 as listed on the GitHub repo.
I run cdk deploy as instructed but I hit an error: 

`Error: Failed to bundle asset DocUnderstanding/WebApp/S3UI/<wbr>UI/Stage, bundle output is located at /home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/cdk.out/asset.<wbr>8f26c22c27562c32d4e256a2e7b480<wbr>dcd2cfc46b20eba02a128f3a197963<wbr>24ae-error: Error: docker exited with status 1<br>--&gt; Command: docker run --rm --security-opt "no-new-privileges:true" --network host -u root -v "/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>ui:/asset-input:delegated" -v "/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/cdk.out/asset.<wbr>8f26c22c27562c32d4e256a2e7b480<wbr>dcd2cfc46b20eba02a128f3a197963<wbr>24ae:/asset-output:delegated" -w "/asset-input" "public.ecr.aws/sam/build-<wbr>nodejs18.x" bash -c "echo \"local bundling failed for /home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/ui and hence building with Docker image\" &amp;&amp; npm install &amp;&amp; npm run build &amp;&amp; rm -fr /asset-input/node_modules &amp;&amp; npm ci --omit=dev &amp;&amp; mkdir -p /asset-output/ &amp;&amp; cp -au /asset-input/* /asset-output/ &amp;&amp; rm -fr /asset-output/.coverage"<br>    at AssetStaging.bundle (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/node_modules/<wbr>aws-cdk-lib/core/lib/asset-<wbr>staging.js:2:619)<br>    at AssetStaging.stageByBundling (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/node_modules/<wbr>aws-cdk-lib/core/lib/asset-<wbr>staging.js:1:5297)<br>    at stageThisAsset (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/node_modules/<wbr>aws-cdk-lib/core/lib/asset-<wbr>staging.js:1:2728)<br>    at Cache.obtain (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/node_modules/<wbr>aws-cdk-lib/core/lib/private/<wbr>cache.js:1:242)<br>    at new AssetStaging (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/node_modules/<wbr>aws-cdk-lib/core/lib/asset-<wbr>staging.js:1:3125)<br>    at new Asset (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/node_modules/<wbr>aws-cdk-lib/aws-s3-assets/lib/<wbr>asset.js:1:1080)<br>    at new UIAssets (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/lib/s3web/ui-<wbr>asset.ts:81:26)<br>    at new UIInfrastructure (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/lib/ui-<wbr>infrastructure.ts:64:30)<br>    at new DusStack (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/lib/dus-stack.<wbr>ts:312:33)<br>    at Object.&lt;anonymous&gt; (/home/ec2-user/environment/<wbr>enhanced-document-<wbr>understanding-on-aws/source/<wbr>infrastructure/bin/dus.ts:44:<wbr>13)<br><br>Subprocess exited with error 1`

**Expected behavior**
CDK should deploy the infrastructure to run the solution. However the documentation doesn't indicate how to customize the values as in the CF deployment, user email, indexer option, etc... 

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0281) - Enhanced Document Understanding on AWS. Version v1.0.0".

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? no
- [ ] Have you checked your [service quotas] yes, not an issue there (https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? never got that far

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
I have tried other avenues like the script to generate the cloud formation templates, but I hit another issue. I have been able to deploy the solution only from the console with default CF template that is linked from the Implementation guide.

Thanks.

**Comment by knihit** [comment]
@jaristizabalc sorry to hear you faced an error. To begin with, we will correct the CDK version in the README.md, it should be 2.103.1 or higher.

On the error you are facing, may I request some information about the OS you are running on? Also do you have Docker Desktop installed and is currently running the docker daemon?

If have an option to checkout the code on AWS Cloud9 IDE and try running `cdk synth` on the Cloud9 terminal. Some initial thought, it seems our local build scripts failed during execution and we have a fall back mechanism on docker images to help it build, but if Docker is not running in the background, we generally see this error.

**Comment by jaristizabalc** [comment]
hello @knihit , thanks for the prompt response, my environment is Cloud9 with Amazon Linux:
`NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
Amazon Linux release 2 (Karoo)`

Looks like docker is running:
`$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES`

 Here is the full output of cdk synth, let me know if you need anything else:
`$ cdk synth------------------------------------------
Script executing from: /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure
------------------------------------------
-----------------------------------------
Running maven build for /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/../lambda/layers/custom-java-sdk-config
-----------------------------------------
-----------------------------------------
Current directory is: /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/lambda/layers/custom-java-sdk-config. Running build
-----------------------------------------
Nov 15, 2023 6:41:32 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: _octo=GH1.1.203561999.1700073692; Path=/; Domain=github.com; Expires=Fri, 15 Nov 2024 18:41:32 GMT; Secure; SameSite=Lax". Invalid 'expires' attribute: Fri, 15 Nov 2024 18:41:32 GMT
Nov 15, 2023 6:41:32 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 15 Nov 2024 18:41:32 GMT; HttpOnly; Secure; SameSite=Lax". Invalid 'expires' attribute: Fri, 15 Nov 2024 18:41:32 GMT
-----------------------------------------
Build complete
-----------------------------------------
WARN AWS_SOLUTIONS_CONSTRUCTS_WARNING:  An override has been provided for the property: partitionKey[name]. Default value: 'id'. You provided: 'CASE_ID'.
Bundling asset DocUnderstanding/RedactApiLambda/Code/Stage...
Nov 15, 2023 6:42:43 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: _octo=GH1.1.1852324079.1700073763; Path=/; Domain=github.com; Expires=Fri, 15 Nov 2024 18:42:43 GMT; Secure; SameSite=Lax". Invalid 'expires' attribute: Fri, 15 Nov 2024 18:42:43 GMT
Nov 15, 2023 6:42:43 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 15 Nov 2024 18:42:43 GMT; HttpOnly; Secure; SameSite=Lax". Invalid 'expires' attribute: Fri, 15 Nov 2024 18:42:43 GMT
WARN AWS_SOLUTIONS_CONSTRUCTS_WARNING:  An override has been provided for the property: defaultRootObject. Default value: 'index.html'. You provided: 'login.html'.
Bundling asset DocUnderstanding/WebApp/S3UI/UI/Stage...
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtual@2.10.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   67 more (@aws-amplify/ui-react, @aws-amplify/ui-react-core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN   react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN   node_modules/@cloudscape-design/components
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN   node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN     react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN     node_modules/@cloudscape-design/components
/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/ValidationError.js:745
  
  

SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:21:47)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.17.1
Error with local bundling Error: Command failed: cd /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui && mkdir -p build && npm install && npm run build
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtual@2.10.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   67 more (@aws-amplify/ui-react, @aws-amplify/ui-react-core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN   react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN   node_modules/@cloudscape-design/components
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN   node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN     react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN     node_modules/@cloudscape-design/components
/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/ValidationError.js:745
  
  

SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:21:47)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.17.1

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at localBundling (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/lib/utils/common-utils.ts:101:32)
    at Object.tryBundle (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/lib/utils/asset-bundling.ts:167:45)
    at AssetStaging.bundle (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:33)
    at AssetStaging.stageByBundling (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:5297)
    at stageThisAsset (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2728)
    at Cache.obtain (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
    at new AssetStaging (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:3125) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 0a 75 70 20 74 6f 20 64 61 74 65 2c 20 61 75 64 69 74 65 64 20 32 37 30 37 20 70 61 63 6b 61 67 65 73 20 69 6e 20 31 33 73 0a 0a 32 37 37 20 70 61 63 ... 308 more bytes>,
    <Buffer 6e 70 6d 20 57 41 52 4e 20 45 52 45 53 4f 4c 56 45 20 6f 76 65 72 72 69 64 69 6e 67 20 70 65 65 72 20 64 65 70 65 6e 64 65 6e 63 79 0a 6e 70 6d 20 57 ... 1906 more bytes>
  ],
  pid: 17259,
  stdout: <Buffer 0a 75 70 20 74 6f 20 64 61 74 65 2c 20 61 75 64 69 74 65 64 20 32 37 30 37 20 70 61 63 6b 61 67 65 73 20 69 6e 20 31 33 73 0a 0a 32 37 37 20 70 61 63 ... 308 more bytes>,
  stderr: <Buffer 6e 70 6d 20 57 41 52 4e 20 45 52 45 53 4f 4c 56 45 20 6f 76 65 72 72 69 64 69 6e 67 20 70 65 65 72 20 64 65 70 65 6e 64 65 6e 63 79 0a 6e 70 6d 20 57 ... 1906 more bytes>
}
local bundling failed for /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui and hence building with Docker image
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtual@2.10.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   67 more (@aws-amplify/ui-react, @aws-amplify/ui-react-core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN   react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN   node_modules/@cloudscape-design/components
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN   node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN     react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN     node_modules/@cloudscape-design/components

up to date, audited 2707 packages in 14s

277 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.2.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
npm notice Run `npm install -g npm@10.2.3` to update!
npm notice 

> intelligent-document-processing-ui@1.0.2 build
> cp ./node_modules/pdfjs-dist/build/pdf.worker.min.js public/ && react-scripts build

/asset-input/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/ValidationError.js:745
  
  

SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/asset-input/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:21:47)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.18.2
/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2
`),localBundling=options.local?.tryBundle(bundleDir,options),!localBundling){const assetStagingOptions={sourcePath:this.sourcePath,bundleDir,...options};switch(options.bundlingFileAccess){case bundling_1().BundlingFileAccess.VOLUME_COPY:new(asset_staging_1()).AssetBundlingVolumeCopy(assetStagingOptions).run();break;case bundling_1().BundlingFileAccess.BIND_MOUNT:default:new(asset_staging_1()).AssetBundlingBindMount(assetStagingOptions).run();break}}}catch(err){const bundleErrorDir=bundleDir+"-error";throw fs().existsSync(bundleErrorDir)&&fs().removeSync(bundleErrorDir),fs().renameSync(bundleDir,bundleErrorDir),new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`)}if(fs_1().FileSystem.isEmpty(bundleDir)){const outputDir=localBundling?bundleDir:AssetStaging.BUNDLING_OUTPUT_DIR;throw new Error(`Bundling did not produce any output. Check that content is written to ${outputDir}.`)}}calculateHash(hashType,bundling,outputDir){if(hashType==assets_1().AssetHashType.CUSTOM||hashType==assets_1().AssetHashType.SOURCE&&bundling){const hash=crypto().createHash("sha256");return hash.update(this.customSourceFingerprint??fs_1().FileSystem.fingerprint(this.sourcePath,this.fingerprintOptions)),bundling&&hash.update(JSON.stringify(bundling)),hash.digest("hex")}switch(hashType){case assets_1().AssetHashType.SOURCE:return fs_1().FileSystem.fingerprint(this.sourcePath,this.fingerprintOptions);case assets_1().AssetHashType.BUNDLE:case assets_1().AssetHashType.OUTPUT:if(!outputDir)throw new Error(`Cannot use \`${hashType}\` hash type when \`bundling\` is not specified.`);return fs_1().FileSystem.fingerprint(outputDir,this.fingerprintOptions);default:throw new Error("Unknown asset hash type.")}}}exports.AssetStaging=AssetStaging,_a=JSII_RTTI_SYMBOL_1,AssetStaging[_a]={fqn:"aws-cdk-lib.AssetStaging",version:"2.103.1"},AssetStaging.BUNDLING_INPUT_DIR="/asset-input",AssetStaging.BUNDLING_OUTPUT_DIR="/asset-output",AssetStaging.assetCache=new(cache_1()).Cache;function renderAssetFilename(assetHash,extension=""){return`asset.${assetHash}${extension}`}function determineHashType(assetHashType,customSourceFingerprint){const hashType=customSourceFingerprint?assetHashType??assets_1().AssetHashType.CUSTOM:assetHashType??assets_1().AssetHashType.SOURCE;if(customSourceFingerprint&&hashType!==assets_1().AssetHashType.CUSTOM)throw new Error(`Cannot specify \`${assetHashType}\` for \`assetHashType\` when \`assetHash\` is specified. Use \`CUSTOM\` or leave \`undefined\`.`);if(hashType===assets_1().AssetHashType.CUSTOM&&!customSourceFingerprint)throw new Error("`assetHash` must be specified when `assetHashType` is set to `AssetHashType.CUSTOM`.");return hashType}function calculateCacheKey(props){return crypto().createHash("sha256").update(JSON.stringify(sortObject(props))).digest("hex")}function sortObject(object){if(typeof object!="object"||object instanceof Array)return object;const ret={};for(const key of Object.keys(object).sort())ret[key]=sortObject(object[key]);return ret}function findSingleFile(directory,archiveOnly){if(!fs().existsSync(directory))throw new Error(`Directory ${directory} does not exist.`);if(!fs().statSync(directory).isDirectory())throw new Error(`${directory} is not a directory.`);const content=fs().readdirSync(directory);if(content.length===1){const file=path().join(directory,content[0]),extension=getExtension(content[0]).toLowerCase();if(fs().statSync(file).isFile()&&(!archiveOnly||ARCHIVE_EXTENSIONS.includes(extension)))return file}}function determineBundledAsset(bundleDir,outputType){const archiveFile=findSingleFile(bundleDir,outputType!==bundling_1().BundlingOutput.SINGLE_FILE);switch(outputType===bundling_1().BundlingOutput.AUTO_DISCOVER&&(outputType=archiveFile?bundling_1().BundlingOutput.ARCHIVED:bundling_1().BundlingOutput.NOT_ARCHIVED),outputType){case bundling_1().BundlingOutput.NOT_ARCHIVED:return{path:bundleDir,packaging:assets_1().FileAssetPackaging.ZIP_DIRECTORY};case bundling_1().BundlingOutput.ARCHIVED:case bundling_1().BundlingOutput.SINGLE_FILE:if(!archiveFile)throw new Error("Bundling output directory is expected to include only a single file when `output` is set to `ARCHIVED` or `SINGLE_FILE`");return{path:archiveFile,packaging:assets_1().FileAssetPackaging.FILE,extension:getExtension(archiveFile)}}}function getExtension(source){for(const ext of ARCHIVE_EXTENSIONS)if(source.toLowerCase().endsWith(ext))return ext;return path().extname(source)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ^
Error: Failed to bundle asset DocUnderstanding/WebApp/S3UI/UI/Stage, bundle output is located at /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/cdk.out/asset.8f26c22c27562c32d4e256a2e7b480dcd2cfc46b20eba02a128f3a19796324ae-error: Error: docker exited with status 1
--> Command: docker run --rm --security-opt "no-new-privileges:true" --network host -u root -v "/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui:/asset-input:delegated" -v "/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/cdk.out/asset.8f26c22c27562c32d4e256a2e7b480dcd2cfc46b20eba02a128f3a19796324ae:/asset-output:delegated" -w "/asset-input" "public.ecr.aws/sam/build-nodejs18.x" bash -c "echo \"local bundling failed for /home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui and hence building with Docker image\" && npm install && npm run build && rm -fr /asset-input/node_modules && npm ci --omit=dev && mkdir -p /asset-output/ && cp -au /asset-input/* /asset-output/ && rm -fr /asset-output/.coverage"
    at AssetStaging.bundle (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:619)
    at AssetStaging.stageByBundling (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:5297)
    at stageThisAsset (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2728)
    at Cache.obtain (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
    at new AssetStaging (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:3125)
    at new Asset (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1080)
    at new UIAssets (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/lib/s3web/ui-asset.ts:81:26)
    at new UIInfrastructure (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/lib/ui-infrastructure.ts:64:30)
    at new DusStack (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/lib/dus-stack.ts:312:33)
    at Object.<anonymous> (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/infrastructure/bin/dus.ts:44:13)

Subprocess exited with error 1`

**Comment by knihit** [comment]
@jaristizabalc - so from the error log it seems the UI project is failing its build. if you switch directory to `source/ui` and run the following 

```
npm install
npm run build
npm run test

```

can you check what do you see there. My expectation is that the UI build should fail, in which case the error in that project would help me reach the root cause.

**Comment by jaristizabalc** [comment]
thanks @knihit , here is the error I got building:

` ~/environment/enhanced-document-understanding-on-aws/source/ui (main) $ npm run build

> intelligent-document-processing-ui@1.0.2 build
> cp ./node_modules/pdfjs-dist/build/pdf.worker.min.js public/ && react-scripts build

/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/ValidationError.js:745
  
  

SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/ec2-user/environment/enhanced-document-understanding-on-aws/source/ui/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:21:47)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.17.1`

**Comment by knihit** [comment]
Ok, have you made any changes in the UI and if you have fork of the repo, I would like to pull that and check.

To troubleshoot further, we can split the commands into 2 separate executions. after `npm install`, can you run the following `cp ./node_modules/pdfjs-dist/build/pdf.worker.min.js public/ `. Check if the pdf.worker.min.js is in the `source/ui/public` folder. Then run `react-scripts build` to see if this fails. In the meantime.

I will also start looking into potential root causes for `SyntaxError: Unexpected end of input`.

**Comment by knihit** [comment]
So I am building on a fresh code checked out from github and I ran `npm run build` without any errors. The node environment versions are as below 

```
npm -v && node -v                
```
```                                                                                                                                          
9.6.7
v18.17.1
```

**Comment by knihit** [comment]
Also can I suggest to create Ubuntu instance instead of AL2 for to check this build with Cloud9.

**Comment by knihit** [comment]
I just ran a new Cloud9 instance with AL2, did checkout from the `mainline`, switched to `source/ui` folder, executed `npm install` and then `npm run build`, and I don't see any failures.

**Comment by jaristizabalc** [comment]
hello, versions are:
10.2.3
v18.17.1

pdf.worker.min.js is in the source/ui/public folder, however I cannot run react-scripts build, command not found, could this be the issue?

`npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtual@2.10.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   67 more (@aws-amplify/ui-react, @aws-amplify/ui-react-core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN   react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN   node_modules/@cloudscape-design/components
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN   node_modules/@cloudscape-design/components/node_modules/react-virtual
npm WARN     react-virtual@"^2.8.2" from @cloudscape-design/components@3.0.424
npm WARN     node_modules/@cloudscape-design/components`

**Comment by knihit** [comment]
The the warnings you mentioned are benign. That is not the cause of the errors you see. Have you made any changes to the UI?

As I mentioned I used AL2 Cloud9 instance and I checked out from the `main` branch of this repo, I am able to run `npm run build` with no issues. The issue you see in the UI is likely a compilation issue.

One additional thing you can try is delete the `node_modules` folder and run `npm install`, `npm run build` post deleting it.

**Comment by jaristizabalc** [comment]
thanks @knihit , I was able to deploy the stack, the fix was to delete node_modules and run npm install/npm run build.

On a different note, if I want to customize the user email/kendra option/workflow config , should I be doing it at
`./source/infrastructure/lib/utils/constants.ts`

**Comment by knihit** [comment]
@jaristizabalc I think the options you are referring are the CloudFormation parmaeters. So `cdk deploy` has a switch `--parameters` to configure the options. This [section in this guide](https://docs.aws.amazon.com/solutions/latest/enhanced-document-understanding-on-aws/launch-the-stack.html) lists the parameters. As an example `cdk deploy --parameters DeployKendraIndex=Yes --parameters WorkflowConfigName=default --parameters NotificationSubscriptionEmail=<email>

For `WorkflowConfigName`, you have the following options out of the box. 
![Screenshot 2023-11-16 at 11 41 59 AM](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/24500178/e675bc67-7ca1-4e67-9af1-e1d23884493a)

Since your initial is resolved, I will close the ticket, if you face any other problems, please create a new issue.
