### ISSUE TITLE
Case max number of documents and processing workflow

### ISSUE THREAD

**Issue by jaristizabalc** [aws-solutions/enhanced-document-understanding-on-aws#13]
**Is your feature request related to a problem? Please describe.**
Hello, currently you can control the number of documents you can have in a case through the workflow-config JSON object, set at deployment time.  However you are stuck with this max amount of documents, and they are only processed for Textract features until all of them are uploaded. 

**Describe the feature you'd like**
I think is a common situation to have  a case type that doesn't always have the same amount of documents, for instance, insurance claims cases can have sometimes  10 invoices , 5 receipts, etc, and the next claim have  1 receipt and 1 invoice. It would be really nice if you could set a max of documents of each type (like it is currently now), but kick off the process for Textract as soon as the document is uploaded.

**Comment by knihit** [comment]
@jaristizabalc thank you for reaching out. The use case you described is a real-life use case. In the upcoming iterations we are considering some features changes to this behavior which should provide more flexibility.

**Comment by jaristizabalc** [comment]
@knihit thank you, I'll keep an eye on that one!
