### ISSUE TITLE
Document and case deletion

### ISSUE THREAD

**Issue by jaristizabalc** [aws-solutions/enhanced-document-understanding-on-aws#14]
**Is your feature request related to a problem? Please describe.**
A case cannot be deleted, likewise a document cannot be removed once it has been uploaded to the case.

**Describe the feature you'd like**
Be able to delete a case, as well as delete a document from a case.   

**Additional context**
Would it be enough to remove the entry on DynamoDB and the files on S3 in order to accomplish a clean delete operation? thank you.

**Comment by knihit** [comment]
@jaristizabalc thank you for reaching out. The `delete` feature is something we are planning for in the future iterations. Please lookout for updates to the solution in the coming months.

In the interim, to answer your question, are you looking to delete all documents and inferences, then what you have stated is correct. If you just don't want the records to be displayed in the front end, deleting the DynamoDB record is enough.

**Comment by jaristizabalc** [comment]
@knihit thank you, any advise on the indexer part? the document entry should be removed on Kendra to avoid null references on the search results.

**Comment by knihit** [comment]
@jaristizabalc, thanks for pointing out, yes the only API to delete documents from Kendra is https://docs.aws.amazon.com/kendra/latest/APIReference/API_BatchDeleteDocument.html. So yes this would have to be called as well.
