### ISSUE TITLE
Some documents fail entity detection due to repeating words

### ISSUE THREAD

**Issue by jamesnixon-aws** [aws-solutions/enhanced-document-understanding-on-aws#34]
**Describe the bug**
When the line where an entity is present contains some words from the entity just before the actual entity, the entity detection fails.

**To Reproduce**
Upload a document with the above conditions to a case with an entity detection workflow

**Expected behavior**
Detection succeeds, or on failure we do not fail the whole workflow.

**Please complete the following information about the solution:**

- [X] Version: [e.g. v1.0.5]

**Comment by ihmaws** [comment]
Resolved as of v1.0.6
