### ISSUE TITLE
Unable to parse command line options: Unrecognized option: --no-transfer-progress

### ISSUE THREAD

**Issue by twocoins-ca** [aws-solutions/enhanced-document-understanding-on-aws#4]
**Describe the bug**
Unable to parse command line options: Unrecognized option: --no-transfer-progress
Subprocess exited with error 1

**To Reproduce**
cdk synth

-----------------------------------------
Current directory is: /home/ec2-user/workspaces/enhanced-document-understanding-on-aws/source/lambda/layers/custom-java-sdk-config. Running build
-----------------------------------------
Unable to parse command line options: Unrecognized option: --no-transfer-progress

usage: mvn [options] [<goal(s)>] [<phase(s)>]

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0281) - Enhanced Document Understanding on AWS. Version v1.0.0".

- [ca-central-1 ] Region: [ca-central-1]

I am using cloud9 as the IDE.

uname -a
Linux ip-10-2-35-238.ca-central-1.compute.internal 4.14.322-244.536.amzn2.x86_64 #1 SMP Wed Aug 16 04:58:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jamesnixon-aws** [comment]
Hi. Can you check which version of maven you have installed (`mvn --version`)? I am not seeing this error with the latest version (3.9.2).
It seems from your error message that you may not have a version of maven which supports the `--no-transfer-progress` flag, which was added in 3.6.1 (https://maven.apache.org/docs/3.6.1/release-notes.html#user-visible-changes).
Please try using the latest version of maven and running `cdk synth` again and see if your issue persists.

**Comment by knihit** [comment]
@twocoins-ca you can also remove that option, removing the option causes more verbose logging during build. Not using the option does not affect the artifacts generated from the `cdk synth`

**Comment by tabdunabi** [comment]
@twocoins-ca, closing this issue. See responses above.
