### ISSUE TITLE
How to opt out The deployment to Amazon Kendra

### ISSUE THREAD

**Issue by twocoins-ca** [aws-solutions/enhanced-document-understanding-on-aws#5]
**Is your feature request related to a problem? Please describe.**
The documentation stated that the deployment to Amazon Kendra is optional. If not deployed the search feature is not available.

How do we do it?

**Describe the feature you'd like**
Any configuration to opt out Kendra?

Thanks in advance for the consideration and hope that we can have a prompt reply soon.

**Comment by knihit** [comment]
@twocoins-ca, there is a cloudformation parameter `DeployKendraIndex`, if you pass the value `No` it would not deploy the Kendra index. To provide explicit instructions, can you please share the command you are using to deploy. A snapshot of the command looks like this: `cdk deploy --parameters DeployKendraIndex=No --parameters .........`

**Comment by knihit** [comment]
@twocoins-ca hope this problem is resolved. If you are still facing issues, please feel free to open a new ticket.
