### ISSUE TITLE
API Schema information request

### ISSUE THREAD

**Issue by Komal-99** [aws-solutions/enhanced-document-understanding-on-aws#64]
Hi  @mukitmomin @knihit , 
I am opening this issue to check if the Request body for RestAPI got updated. Not able to find it but my previous code throughs me an error of Invalid Request Body.
```
def create_case(case_id: str = None):
    if not case_id:
        raise ValueError("`case_id` is required")
    request_body = {
            "caseName": case_id,
        }
    get_case_api = f"{REST_API_ENDPOINT}/case"
    try:
        region = "us-east-1"  # Update this with your AWS region
        service = "execute-api"
        # Sign the request using AWS Signature Version 4
        aws_auth = AWS4Auth(ACCESS_KEY,SECRET_KEY, region, service, session_token=session_token)
        headers = {
        "Authorization": f"Bearer {session_token}",
        "User-Agent": USER_AGENT,
        "Content-Type": "application/json"
    }
        # Send the request with authentication
        response = requests.post(get_case_api,data=json.dumps(request_body), headers=headers)

        # Check if the response was successful
        if response.status_code == 200:
            # Parse the JSON data from the response body
            data = response.json()
            case_id = data.get('caseId')
            return case_id
        else:
            print(f"Error: {response.status_code} - {response.text}")

    except NoCredentialsError:
        print("AWS credentials not found or invalid.")
        return None
```
When Passing a String ```case_id```  due to which case not getting created and I am not able to use the service. 
![image](https://github.com/user-attachments/assets/99b8004a-419c-4cd3-a2c7-c9e7c1cc1314)
 

_Originally posted by @Komal-99 in https://github.com/aws-solutions/enhanced-document-understanding-on-aws/issues/31#issuecomment-2267525886_

**Comment by knihit** [comment]
So you can export the swagger or Open API spec if you have deployed the solution from the API Gateway web console. Here is the API Gateway documentation on how you can do it - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html

**Comment by Komal-99** [comment]
Hi , 
 Not able to resolve it till now, can you elaborate more,  will exporting swagger gives me the JSON payload expected to pass to the API?

**Comment by knihit** [comment]
The Swagger will give you the JSON schema for the payload.

**Comment by knihit** [comment]
You can also capture the actual payload, if you have the solution deployed and while using the web inspector in browsers like chrome and firefox.

**Comment by Komal-99** [comment]
Hi @knihit , 
Thanks, I downloaded Swagger files and got an idea of the payload. However, we don't have a deployed solution as we need to use only the API integrated into our solution.

While I am trying the New payload from the Python script it shows ```403 error: forbidden``` on the Rest API request to create caseID  Figure 1 and when calling it from postman it gives a ```CustomExecutionError: Cannot read properties of undefined (reading 'concat')``` which on my research is same as Undefined because Case is not getting Creating. figure 2 
![image](https://github.com/user-attachments/assets/7e25aaab-85c2-424d-947f-b0b508008479)

![image](https://github.com/user-attachments/assets/0d77461e-5ce6-45c9-8114-89574b7fbb47)

looking for guidance and help :)

**Comment by Komal-99** [comment]
Hi @knihit @mukitmomin looking for an answers if you could help.

**Comment by mukitmomin** [comment]
The format of the Authorization header is incorrect i believe. You do not need `Bearer`, just the `{"Authorization" : <token>}` should be fine. You can try using this function as a sample

```
# create a function to parse a command line argument for case name
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--case_name", help="Name of the case to be created", required=False, default=DEFAULT_CASE_NAME)
    args = parser.parse_args()
    return args


def create_case(case_name: str = None):
    if not case_name:
        case_name = DEFAULT_CASE_NAME

    create_case_endpoint = f"{REST_API_ENDPOINT}/case"
    headers = {"Authorization": token, "User-Agent": USER_AGENT, "Content-Type": "application/json"}

    try:
        response = requests.post(
            create_case_endpoint, headers=headers, json={"caseName": case_name, "enableBackendUpload": False}
        )

        if response.status_code == 200:
            return response.json()

    except Exception as e:
        raise e


if __name__ == "__main__":
    args = parse_args()
    response = create_case(args.case_name)

    pprint(response)
```

I have tested that bit of code with the v2 release of EDU and it is working.

**Comment by Komal-99** [comment]
How to get an Authorization token? I am using a session token. Because I removed the Authorization from all the APIs by editing the API from API gateway.

**Comment by mukitmomin** [comment]
The upload-document lambda function has a method to create cases. To ensure only valid users can create cases the Authorization jwt token is decoded to extract the cognito userId claim jwt token, using this [function](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/26e3f46e5f1addf5f3daf95e857c5f63fc0d20da/source/lambda/layers/common-node-lib/cognito/decode-jwt-token.js#L37) in the common-node-lib. 

If you have removed the Authorization mechanism then you have to modify the logic for validating case creation, as implemented [here](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/26e3f46e5f1addf5f3daf95e857c5f63fc0d20da/source/lambda/upload-document/index.js#L39). The error you are seeing is coming from [this line](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/26e3f46e5f1addf5f3daf95e857c5f63fc0d20da/source/lambda/upload-document/utils/create-case.js#L46) because the userId in that function is undefined as you removed the Authorization mechanism.
