### ISSUE TITLE
Can we have dedicated class /function to pass the bounding box of entity and it highlights the same on document in UI

### ISSUE THREAD

**Issue by aakash086** [aws-solutions/enhanced-document-understanding-on-aws#77]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**
I need to utilize the function or class which can take in the bounding box details of entity and it highlights the same on document in UI.

**Additional context**

**Comment by aakash086** [comment]
Is there a function in the library which generates the PDF with rendered bounding box ?

**Comment by OmarRad** [comment]
@aakash086 The bounding boxes are placed using HTML+CSS. The code can be found [here](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/ui/src/components/Pdf/Pdf.tsx#L93-L130). You may use it wherever needed.

**Comment by knihit** [comment]
@aakash086 closing issue with the resolution provided by @OmarRad
