### ISSUE TITLE
Their is some Flag issue in Case Status

### ISSUE THREAD

**Issue by Komal-99** [aws-solutions/enhanced-document-understanding-on-aws#79]
**Describe the bug**
 
![image](https://github.com/user-attachments/assets/4c95f414-926d-403b-9ef2-fc0af7bada3c)
Here All Failed cases show Text extracted but the Complete ones show Null, which means no text extraction is performed on this. There is some issue in the flagging function It should be opposite to the current implementation. Also Need Help that After Text extraction Still Raw text is not getting detected in My solution, what could be the Root Cause?

**Expected behavior**
For Cases where Document text extraction is Complete, It should show the Status as complete

**Please complete the following information about the solution:**

- [X] Version: v1.1.5

- [X] Region: us-southeast-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [X] Were there any errors in the CloudWatch Logs?

**Comment by mukitmomin** [comment]
Hi @Komal-99 thanks for opening the issue. We will investigate and reach out to you for more info or questions.

**Comment by Komal-99** [comment]
Also @mukitmomin   
Can You help in reviewing this code function , 
``` 
def start_job(token: str, case_id: str):
    # Prepare the request body with the provided case_id
    request_body = {
        "caseId": case_id
    }
    
    # The API endpoint for starting the job
    start_job_api = f"{REST_API_ENDPOINT}/case/start-job"
    
    # Headers with the Authorization token and Content-Type
    headers = {
        "Authorization": token,
        "Content-Type": "application/json"
    }
    # Send the POST request
    response = requests.post(start_job_api, json=request_body, headers=headers)
    
    try:
        # Check if the request was successful
        if response.status_code == 200:
            # Parse and return the JSON response
            response_data = response.json()
            print(f"Response Data: {response_data}")
            return response_data
        else:
            # Handle non-200 status codes
            print(f"Error in start job: {response.status_code} - {response.text}")
            return None
    except Exception as e:
        print(f"Exception: {e}")
        print(f"Response Content: {response.content}")
        return None
```
for Starting Job after Uploading the document Successfully I got Logs as 
![image](https://github.com/user-attachments/assets/fae6aff6-70bb-4ae3-b476-2d6b3f5b2f82)
 
 But As mentioned above On UI It shows Complete , but It shows ```Error: 400 - CustomExecutionError: Error retrieving references for the specified caseId and documentId.```  error while making Get request to fetch details using Postman and on UI as follows all  Entity blank while API status is 200.
 
 
![image](https://github.com/user-attachments/assets/2b37a5a9-708f-4159-b194-5eb99593f14f)
![image](https://github.com/user-attachments/assets/b1df8c73-6c46-4f6b-ac03-94c4f3cdc94b)

**Comment by mukitmomin** [comment]
After uploading the document, you have to click start job to start the processing.

**Comment by mukitmomin** [comment]
Hello, after uploading the documents, please send a POST request to the `/case/start-job` endpoint. In the request body you have to include the caseId. The logic is handled in the `upload-document` lambda function, as seen [here](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/lambda/upload-document/index.js#L73). The code you shared looks correct. Please make sure you are providing the correct caseId to prevent errors.

Marking this issue as closed.
